openapi: 3.0.0
info:
  title: Product Service API
  description: API documentation for managing products in the product catalog.
  version: 1.0.0
servers:
  - url: https://1n09q877x5.execute-api.eu-west-1.amazonaws.com/prod/products
    description: server
paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The product ID
                    title:
                      type: string
                      description: The product name
                    description:
                      type: string
                      description: The product description
                    image:
                      type: string
                      description: The product link of image
                    price:
                      type: integer
                      description: The product price
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The product name
                description:
                  type: string
                  description: The product description
                image:
                  type: string
                  description: The product link of image
                price:
                  type: integer
                  description: The product price
                count:
                  type: integer
                  description: The number of products in stock
              required:
                - title
                - description
                - price
                - count
      responses:
        "200":
          description: The product was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created product
                  title:
                    type: string
                    description: The product name
                  description:
                    type: string
                    description: The product description
                  image:
                    type: string
                    description: The product link of image
                  price:
                    type: integer
                    description: The product price
                  count:
                    type: integer
                    description: The number of products in stock
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
  /products/{productId}:
    get:
      summary: Get details of a specific product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        "200":
          description: The product details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The product ID
                  title:
                    type: string
                    description: The product name
                  description:
                    type: string
                    description: The product description
                  image:
                    type: string
                    description: The product link of image
                  price:
                    type: integer
                    description: The product price
        "404":
          description: Product not found
  /import:
    get:
      summary: Get a signed URL for uploading a CSV file
      description: Returns a signed URL that can be used to upload a CSV file to the S3 bucket.
      parameters:
        - name: name
          in: query
          description: The name of the CSV file to upload
          required: true
          schema:
            type: string
            example: filename.csv
      responses:
        "200":
          description: A signed URL for uploading the file
          content:
            text/plain:
              schema:
                type: string
                example: https://j7pd0a74a0.execute-api.eu-west-1.amazonaws.com/prod/import?name=filename.csv
        "400":
          description: Bad request. The file name is missing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File name is required
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal Server Error
