# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rstanya
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shop-be
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handlers/getProductsById.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
